language: cpp
compiler: gcc

os: linux
dist: xenial
#addons:
#  apt:
#    packages: lcov

script:
  - mkdir -p build && cd build
  - cmake -DCODE_COVERAGE=ON -DCMAKE_BUILD_TYPE=Debug ..
  - cmake --build . --config Debug -- -j $(nproc)
  - ctest -j $(nproc) --output-on-failure

after_success:
#  - lcov --directory . --capture --output-file coverage.info
#  - lcov --remove coverage.info '*/test/*' '/usr/*' "${HOME}"'/.cache/*' --output-file coverage.info
#  - lcov --list coverage.info
#  - bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"

#notifications:
#  email:
#    - voxelheim@gmail.com